# spring MariaDB Connect
spring:
  datasource:
    url: jdbc:mariadb://bucwith.cpominkx6ixa.ap-northeast-2.rds.amazonaws.com:3306/bucwith
    username: root
    password: BUCWITH123
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 178000
  redis:
    host: localhost
    port: 6379
  profiles:
    include: oauth
#    active: local

#      connectionTimeout: 10000 #30000ms
#      maximumPoolSize: 20 #?? 10
#      validationTimeout: 1000 #5000ms, connectionTimeout ?? ??? ?
#
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none

security:
  basic:
    enabled: true

server:
  port: 8888